name: nst_env
channels:
  - defaults
dependencies:
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.4.0
  - scipy=1.10.0
  - tensorflow=2.10.0
  - tqdm=4.65.0
  - ipykernel=6.19.2
  - pip:
    - sewar
